services:
  Braunstetter\MenuBundle\Twig\Extension:
    tags: [ 'twig.extension' ]
    arguments:
      - '@Braunstetter\MenuBundle\Services\Menu'

  Braunstetter\MenuBundle\Services\Menu:
    arguments:
      - !tagged_iterator menu
      - '@request_stack'
      - '@router'
      - '@Twig_Environment'