services:
  Braunstetter\MenuBundle\Twig\Extension:
    tags: [ 'twig.extension' ]
    arguments:
      - '@Braunstetter\MenuBundle\Services\Menu'

  Braunstetter\MenuBundle\Services\Resolver\AbstractMenuResolver:
    abstract: true
    arguments:
      - !tagged_iterator menu
      - '@request_stack'
      - '@router'

  Braunstetter\MenuBundle\Services\Resolver\MenuResolver:
    parent: Braunstetter\MenuBundle\Services\Resolver\AbstractMenuResolver

  Braunstetter\MenuBundle\Services\Resolver\BreadcrumbsResolver:
    parent: Braunstetter\MenuBundle\Services\Resolver\AbstractMenuResolver

  Braunstetter\MenuBundle\Services\Menu:
    arguments:
      - '@Braunstetter\MenuBundle\Services\Resolver\MenuResolver'
      - '@Braunstetter\MenuBundle\Services\Resolver\BreadcrumbsResolver'